pib/dynamic/PolicyManagementSystem/Controllers/PolicyManagementController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PolicyManagementDataAccess;
using PolicyManagementDataAccess.Context;
using PolicyManagementSystem.Controllers.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using Microsoft.AspNet.Identity;


namespace PolicyManagementSystem.Controllers
{
    [Authorize]
    public class PolicyManagementController : Controller
    {
        private IUserAccountRepository _userAccountRepository;
        private IPolicyApplicationRepository _applicationRegistrationRepository;
        private IClientEngagementRepository _clientEngagementRepository;
        private IPolicyManagementRepository _policyManagementRepository;
        //  private IPolicyApplicationRepository _policyApplicationRepository;
        private IWebHostEnvironment _env;
        public PolicyManagementController(IPolicyManagementRepository policyManagementRepository, IPolicyApplicationRepository applicationRegistrationRepository,
            IClientEngagementRepository clientEngagementRepository, IUserAccountRepository userAccountRepository)
        {
            _userAccountRepository = userAccountRepository;
            _applicationRegistrationRepository = applicationRegistrationRepository;
            _clientEngagementRepository = clientEngagementRepository;
            _policyManagementRepository = policyManagementRepository;
          //  _policyApplicationRepository = policyApplicationRepository;
        }

        public IActionResult Index()
        {
            var notificationList = _clientEngagementRepository.GetBrokerNotificationList();
            var model = new PolicyApplicationViewModel() { BrokerNotificationList = notificationList };

            return View("~/Pages/PolicyManagement/Index.cshtml", model);
        }

        public IActionResult ViewPolicy(int currentPage, string searchValue)
        {
            var notificationList = _clientEngagementRepository.GetBrokerNotificationList();
            var model = new PolicyManagementViewModel() { BrokerNotificationList = notificationList };
            var members = _policyManagementRepository.MemberProposerGetList(currentPage, searchValue, 20);
            model.MemberProposerList = members;
            model.CurrentPage = currentPage;

            return View("~/Pages/PolicyManagement/PolicyList.cshtml", model);
        }
        public IActionResult PolicyMembersEdit(int currentPage, string searchValue)
        {
            var notificationList = _clientEngagementRepository.GetBrokerNotificationList();
            var model = new PolicyManagementViewModel() { BrokerNotificationList = notificationList };
            var members = _policyManagementRepository.MemberProposerGetList(currentPage, searchValue, 20);
            model.MemberProposerList = members;
            model.CurrentPage = currentPage;

            return View("~/Pages/PolicyManagement/PolicyMembersEdit.cshtml", model);
        }

        [HttpPut("{id}")]
        public IActionResult Edit(int id, [FromBody] PolicyApplicationViewModel model)
        {
           // var user = _userAccountRepository.GetUser(id);

            return View("~/Pages/PolicyManagement/Edit.cshtml", model);
        }

        public IActionResult PolicyList(int memPropNum)
        {
            var notificationList = _clientEngagementRepository.GetBrokerNotificationList();
            var model = new PolicyManagementViewModel() { BrokerNotificationList = notificationList };

            var memberProposer = _policyManagementRepository.MemberProposerGetById(memPropNum);

            //Get principal member

            return View("~/Pages/PolicyManagement/PolicyList.cshtml", model);
        }
        [HttpPost]
        public IActionResult AmandPolicy(PolicyApplicationViewModel model, string submit)
        {
            try
            {
                //Start with the business rules before we start adding
                if (model.Beneficiary.Idnum == model.PrincipalMemberDetails.Idnum)
                {
                    ModelState.AddModelError("error", "Beneficiary ID must not be the same as the principal member");

                    return View("~/Pages/PolicyApplication/Create.cshtml", model);
                }

                if (model.MemberProposer.RelationToPrincipalMember == "Other(Specify)")
                {
                    model.MemberProposer.RelationToPrincipalMember = model.RelationOther;
                }

                //Get the logged in userId
                var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

                //Add the premium payer details
                model.MemberProposer.UserId = Guid.Parse(userId);
                model.MemberProposer.Status = "Review";

                var memPropKey = _applicationRegistrationRepository.AddMemberProposer(model.MemberProposer);

                //Add Banking details
                if (model.Banking.DoBankName == "Other")
                {
                    model.Banking.DoBankName = model.OtherBankName;
                }

                model.Banking.CollectSurname = model.MemberProposer.Surname;
                model.Banking.CollectIdnum = model.MemberProposer.Idnum;
                model.Banking.CollectStart = int.Parse(model.CommencementDate.ToString("yyyyMMdd"));
                model.Banking.MemPropKey = memPropKey;
                model.Banking.UserId = Guid.Parse(userId);

                var env = _env;
                var verificationLink = Url.Action("VerifyPolicy", "PolicyApplication", new { id = memPropKey }, Request.Scheme);

                var memColKey = _applicationRegistrationRepository.AddBankingDetails(model.Banking, model.MemberProposer.FirstName, env.WebRootPath, verificationLink);

                //Add the Principal details
                model.PrincipalMemberDetails.CoverId = model.CoverID;
                model.PrincipalMemberDetails.MemPropKey = memPropKey;
                model.PrincipalMemberDetails.InsInterest = "Principal";
                model.PrincipalMemberDetails.MemColKey = memColKey;
                model.PrincipalMemberDetails.UserId = Guid.Parse(userId);

                var PrincipalMemGrpKey = _applicationRegistrationRepository.AddMemberGroup(model.PrincipalMemberDetails);

                //Add Beneficiary
                model.Beneficiary.UserId = Guid.Parse(userId);
                model.Beneficiary.MemPropNum = memPropKey;

                _applicationRegistrationRepository.AddBeneficiary(model.Beneficiary);

                //Add spouse Details if filled in the form
                if (!string.IsNullOrEmpty(model.SpouseDetails.ContactPerson))
                {
                    model.SpouseDetails.CoverId = model.CoverID;
                    model.SpouseDetails.MemPropKey = memPropKey;
                    model.SpouseDetails.UserId = Guid.Parse(userId);
                    model.SpouseDetails.InsInterest = "Spouse";
                    model.SpouseDetails.MemColKey = memColKey;
                    _applicationRegistrationRepository.AddMemberGroup(model.SpouseDetails);
                }

                //Add children if added
                if (!string.IsNullOrEmpty(model.ChildrenDetails.FirstOrDefault().Idnum))
                {
                    foreach (var child in model.ChildrenDetails)
                    {
                        child.CoverId = model.CoverID;
                        child.MemPropKey = memPropKey;
                        child.UserId = Guid.Parse(userId);
                        child.InsInterest = "Child";
                        child.MemColKey = memColKey;

                        //Check if the child is older than 21 years
                        //var birthday = DateTime.ParseExact(child.Idnum.Substring(0, 6), "yyMMdd", null);

                        //var age = CalculateAge(birthday);

                        //if(age > 21)
                        //{
                        //    ModelState.AddModelError("", "Child age must not be greater than 21");

                        //    var errmodel = new PolicyApplicationViewModel() { BrokerNotificationList = _clientEngagementRepository.GetBrokerNotificationList() };

                        //    return View("~/Pages/PolicyApplication/Create.cshtml", errmodel);
                        //}

                        _applicationRegistrationRepository.AddMemberGroup(child);
                    }
                }
                //Add extended family if added
                if (!string.IsNullOrEmpty(model.ExtendedFamilies.FirstOrDefault().Idnum))
                {
                    foreach (var fam in model.ExtendedFamilies)
                    {
                        fam.MemPropKey = memPropKey;
                        fam.InsInterest = "Extended Family";
                        fam.UserId = Guid.Parse(userId);
                        fam.MemColKey = memColKey;

                        _applicationRegistrationRepository.AddMemberGroup(fam);
                    }
                }

                //Save the signature
                byte[] bytes = Convert.FromBase64String(model.base64String.Split(',')[1]);

                var filePath = $"{_env.WebRootPath}\\Signatures\\Signature" + memPropKey + ".png";

                using (var imageFile = new System.IO.FileStream(filePath, FileMode.Create))
                {
                    imageFile.Write(bytes, 0, bytes.Length);
                    imageFile.Flush();
                }

                //Add Compliance
                model.Compliance.MemPropKey = memPropKey;
                model.Compliance.UserId = Guid.Parse(userId);
                model.Compliance.PremiumPayerSignature = filePath;

                _applicationRegistrationRepository.AddMemberComplaince(model.Compliance);

pib/dynamic/PolicyManagementSystem/Pages/PolicyManagement/AddChildren.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace PolicyManagementSystem.Pages.PolicyManagement
{
    public class AddChildrenModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

pib/dynamic/PolicyManagementSystem/Pages/PolicyManagement/AddSpouse.cshtml
@model PolicyManagementSystem.Controllers.Models.PolicyApplicationViewModel
@{

}
<!-- ============================================================== -->
<!-- pageheader -->
<!-- ============================================================== -->
<div class="row">
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
        <div class="page-header">
            <h2 class="pageheader-title">Policy Management</h2>
            <p class="pageheader-text"></p>
            <div class="page-breadcrumb">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        @*<li class="breadcrumb-item"><a href="#" class="breadcrumb-link">Dashboard</a></li>*@
                        <li class="breadcrumb-item"><a href="#" class="breadcrumb-link">Policy Management</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Amendments Allowed</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <!-- ============================================================== -->
    <!-- basic table  -->
    <!-- ============================================================== -->
    @using (Html.BeginForm("Create", "PolicyManagement", FormMethod.Post))
    {
        <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
            <div class="card">
                <h5 class="card-header">Add Spouse</h5>
                <div class="card-body" style="width: 1040px;">
                    <div class="table-responsive">
                        <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12 mb-5">
                            <div class="tab-regular">
                                <ul class="nav nav-tabs " id="myTab" role="tablist">
                                   
                                        <li class="nav-item">
                                            <a class="nav-link active" id="contact-tab" data-toggle="tab" href="#tab3" role="tab" aria-controls="contact" aria-selected="false">Spouse Details</a>
                                        </li>

                                 
                                </ul>
                                <div class="tab-content" id="myTabContent">
                                  
                                    <div class="tab-pane fade show active" id="tab3" role="tabpanel" aria-labelledby="contact-tab">
                                       
                                        <div class="form-group">
                                            @Html.TextBoxFor(x => x.SpouseDetails.ContactPerson, new { @class = "form-control", placeholder = "Full Names" })
                                        </div>
  
                                        <div class="form-group">
                                            @Html.TextBoxFor(x => x.SpouseDetails.Surname, new { @class = "form-control", placeholder = "Surname"})
                                        </div>
                                        <div class="form-group">
                                            @Html.TextBoxFor(x => x.SpouseDetails.Idnum, new { @class = "form-control", placeholder = "Identity No." })
                                        </div>

                                        <a href="#tab5" class="btn btn-secondary" style="background-color: #4656e9!important; border-color:none!important">Amend</a>
                                    </div>
                                    
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
    <!-- ============================================================== -->
    <!-- end basic table  -->
    <!-- ============================================================== -->
</div>

pib/dynamic/PolicyManagementSystem/Pages/PolicyManagement/ChangeContactDetails.cshtml
@model PolicyManagementSystem.Controllers.Models.PolicyManagementViewModel
@{

}
<!-- ============================================================== -->
<!-- pageheader -->
<!-- ============================================================== -->
<div class="row">
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
        <div class="page-header">
            <h2 class="pageheader-title">Policy Management</h2>
            <p class="pageheader-text"></p>
            <div class="page-breadcrumb">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        @*<li class="breadcrumb-item"><a href="#" class="breadcrumb-link">Dashboard</a></li>*@
                        <li class="breadcrumb-item"><a href="#" class="breadcrumb-link">Policy Management</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Amendments Allowed</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <!-- ============================================================== -->
    <!-- basic table  -->
    <!-- ============================================================== -->
    @using (Html.BeginForm("ChangeContactDetails", "PolicyManagement", FormMethod.Post))
    {
        <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
            <div class="card">
                <h5 class="card-header">Amend Details</h5>
                <div class="card-body" style="width: 1040px;">
                    <div class="table-responsive">
                        <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12 mb-5">
                            <div class="tab-regular">
                                <ul class="nav nav-tabs " id="myTab" role="tablist">

                                    <li class="nav-item">
                                        <a class="nav-link active" id="member-tab" data-toggle="tab" href="#tab1" role="tab" aria-controls="member" aria-selected="false">Contact Details</a>
                                    </li>

                                </ul>
                                <div class="tab-content" id="myTabContent">
                                    <div class="tab-pane fade show active" id="tab1" role="tabpanel" aria-labelledby="member-tab">
                                        <div class="form-group">
                                          @*  @Html.TextBoxFor(x => x.MemberProposer.FirstName, new { @class = "form-control", placeholder = "First Name", @readonly = "readonly" })*@
                                            @Html.LabelFor(x => x.MemberProposer.FirstName, new { @class = "control-label" })
                                        </div>
                                        <div class="form-group">
                                            @*@Html.TextBoxFor(x => x.MemberProposer.Surname, new { @class = "form-control", placeholder = "Surname", @readonly = "readonly" })*@
                                             @Html.LabelFor(x => x.MemberProposer.Surname, new { @class = "control-label" })
                                        </div>
                                        <div class="form-group">
                                            @*@Html.TextBoxFor(x => x.MemberProposer.Idnum, new { @class = "form-control", placeholder = "SA ID/Passport", @readonly = "readonly" })*@
                                            @Html.LabelFor(x => x.MemberProposer.Idnum, new { @class = "control-label" })
                                        </div>
                                        <div class="form-group">
                                            @Html.TextBoxFor(x => x.MemberProposer.ContactPhone, new { @class = "form-control", placeholder = "Cell number" })
                                        </div>
                                        <div class="form-group">
                                            @Html.TextBoxFor(x => x.MemberProposer.ContactEmail, new { @class = "form-control", placeholder = "Email" })<br />
                                        </div>

                                        <a href="#" class="btn btn-secondary" style="background-color: #4656e9 !important; border-color: #4656e9 !important">Amend</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    }
    <!-- ============================================================== -->
    <!-- end basic table  -->
    <!-- ============================================================== -->
</div>
<p>
    @ViewBag.userid
</p>

pib/dynamic/PolicyManagementSystem/Pages/PolicyManagement/Index.cshtml
@{

}
<!-- ============================================================== -->
<!-- pageheader -->
<!-- ============================================================== -->
<div class="row">
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
        <div class="page-header">
            <h2 class="pageheader-title">Policy Management</h2>
            <p class="pageheader-text"></p>
            <div class="page-breadcrumb">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        @*<li class="breadcrumb-item"><a href="#" class="breadcrumb-link">Dashboard</a></li>*@
                        <li class="breadcrumb-item"><a href="#" class="breadcrumb-link">Policy Management</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Amendments Allowed</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <!-- ============================================================== -->
    <!-- basic table  -->
    <!-- ============================================================== -->

    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
        @*<div class="card">*@
        <h5 class="card-header">Amendments Allowed</h5>
            @*<div class="card-body">*@
                <div class="table-responsive">
                    @*<a class="btn btn-primary btn-block" style="color:white" asp-controller="PolicyApplication" asp-action="Create">Create a policy</a>*@
                    <br />
                    <div class="row">
                        <div class="col-xl-4 col-lg-4 col-md-6 col-sm-12 col-12">
                            <div class="card">
                                <div class="card-body">
                                    <p class="card-text">The new added contact details are verified before the request is lodged into the system. OTP Sent to cell number and emails</p>
                                    <a asp-controller="PolicyManagement" asp-action="PolicyMembersEdit" class="btn btn-primary">Amend</a>
                                </div>
                                <div class="card-footer d-flex">
                                    <b>Contact details</b>
                                </div>
                            </div>
                        </div>
                        <div class="col-xl-4 col-lg-4 col-md-6 col-sm-12 col-12">
                            <div class="card">
                                <div class="card-body">
                                    <p title="The policy owner creates a letter on the system which is stored in the system DB, agree to the terms and conditions, and sign the letter" class="card-text">The policy owner creates a letter on the system which is stored in the system DB, agree to the terms ...</p>
                                    <a asp-controller="PolicyManagement" asp-action="PolicyCancellation" class="btn btn-primary">Amend</a>
                                </div>
                                <div class="card-footer d-flex">
                                    <b>Policy cancellations</b>
                                </div>
                            </div>
                        </div>
                        <div class="col-xl-4 col-lg-4 col-md-6 col-sm-12 col-12">
                            <div class="card">
                                <div class="card-body">
                                    <p class="card-text">Add spouse information and other relevant information including the proof of marriage to the principal member</p>
                                    <a asp-controller="PolicyManagement" asp-action="AddSpouse" class="btn btn-primary">Amend</a>
                                </div>
                                <div class="card-footer d-flex">
                                    <b>Add a Spouse to policy</b>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xl-4 col-lg-4 col-md-6 col-sm-12 col-12">
                            <div class="card">
                                <div class="card-body">
                                    <p class="card-text">System updates the policy payments methods and new Premium’s payer once request has gone through the channels and is approved.</p>
                                    <a asp-controller="PolicyManagement" asp-action="ChangePremiumPayer" class="btn btn-primary">Amend</a>
                                </div>
                                <div class="card-footer d-flex">
                                    <b>Change of premium payer details</b>
                                </div>
                            </div>
                        </div>
                        <div class="col-xl-4 col-lg-4 col-md-6 col-sm-12 col-12">
                            <div class="card">
                                <div class="card-body">
                                    <p class="card-text">The policy owner creates a letter on the system which is stored in the system DB, agree to the terms and conditions, and sign the letter</p>
                                    <a asp-controller="PolicyManagement" asp-action="AddRemoveChildren" class="btn btn-primary">Amend</a>
                                </div>
                                <div class="card-footer d-flex">
                                    <b>Add or remove children</b>
                                </div>
                            </div>
                        </div>
                        <div class="col-xl-4 col-lg-4 col-md-6 col-sm-12 col-12">
                            <div class="card">
                                <div class="card-body">
                                    <p title="The policy owner or broker lodges the request. Cash – once verification officer has approved the change, the system updates policy method of payment. Debit order – policy owner completes the debit order form online and sign it. Stop order – policy owner or broker chooses any of the Stop order forms to make lodge the changes, stop order form, stop order increase, stop order reduce or stop order cancellation." class="card-text">
                                        <b>Cash</b> – once verification officer has approved the change, the system updates policy method of payment. 
                                        <b>Debit order</b> – policy owner completes the debit order form ...
                                    </p>
                                    <a asp-controller="PolicyManagement" asp-action="ChangePaymentMethod" class="btn btn-primary">Amend</a>
                                </div>
                                <div class="card-footer d-flex">
                                    <b>Change of Payment method</b>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xl-4 col-lg-4 col-md-6 col-sm-12 col-12">
                            <div class="card">
                                <div class="card-body">
                                    <p class="card-text">
                                        Select the policy package, signs and submit the request. Once the changes are approved the old policy package is saved under policy history and shows the new upgrade
                                    </p>
                                    <a asp-controller="PolicyManagement" asp-action="UpgradePolicy" class="btn btn-primary">Amend</a>
                                </div>
                                <div class="card-footer d-flex ">
                                    <b>Upgrade of policy</b>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xl-4 col-lg-4 col-md-6 col-sm-12 col-12">
                            <div class="card">
                                <div class="card-body">
                                    <p class="card-text">
                                        View all policy and search for the policy
                                    </p>
                                    <a asp-controller="PolicyManagement" asp-action="ViewPolicy" class="btn btn-primary">ViewPolicy</a>
                                </div>
                                <div class="card-footer d-flex ">
                                    <b>View policy list</b>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            @*</div>*@
        @*</div>*@
    </div>
    <!-- ============================================================== -->
    <!-- end basic table  -->
    <!-- ============================================================== -->
</div>

pib/dynamic/PolicyManagementSystem/Pages/PolicyManagement/PolicyCancelation.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

pib/dynamic/PolicyManagementSystem/Pages/PolicyManagement/UpgradePolicy.cshtml
@model PolicyManagementSystem.Controllers.Models.PolicyApplicationViewModel
@{

}
<!-- ============================================================== -->
<!-- pageheader -->
<!-- ============================================================== -->
<div class="row">
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
        <div class="page-header">
            <h2 class="pageheader-title">Policy Management</h2>
            <p class="pageheader-text"></p>
            <div class="page-breadcrumb">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        @*<li class="breadcrumb-item"><a href="#" class="breadcrumb-link">Dashboard</a></li>*@
                        <li class="breadcrumb-item"><a href="#" class="breadcrumb-link">Policy Management</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Amendments Allowed</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>

@*@using (Html.BeginForm("Create", "PolicyManagement", FormMethod.Post))*@
@*//{*@
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
        <div class="card">
            <h5 class="card-header">Upgrade of policy</h5>
            <div class="card-body" style="width: 1040px;">
                <div class="table-responsive">
                    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12 mb-5">
                        <div class="tab-regular">
                            <ul class="nav nav-tabs " id="myTab" role="tablist">
                                <li class="nav-item">
                                    <a class="nav-link active" id="Payment-tab" data-toggle="tab1" href="#tab1" role="tab" aria-controls="paymentmethod" aria-selected="false">Policy Details</a>
                                </li>
                            </ul>
                            <div class="tab-content" id="myTabContent">
                                <div class="tab-pane fade show active" id="tab1" role="tabpanel" aria-labelledby="Payment-tab">
                                   
                                    <div class="form-group">
                                     
                                    </div>
    
                                <a href="#" class="btn btn-secondary" style="background-color: #4656e9 !important; border-color: #4656e9 !important">Amend</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
@*//}*@
<!-- ============================================================== -->
<!-- end basic table  -->
<!-- ============================================================== -->
</div>