pib/dynamic/PolicyManagementSystem/Controllers/PolicyApplicationController.cs
using AspNetCore.Reporting;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Reporting.WinForms;
using PolicyManagementDataAccess;
using PolicyManagementDataAccess.Context;
using PolicyManagementDataAccess.Helpers;
using PolicyManagementSystem.Controllers.Models;
using PolicyManagementModels.PrincipalMemberDetails;
using AutoMapper;
using System;
using System.Collections.Generic;
using System.Data;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Security.Claims;
using Microsoft.AspNetCore.Identity;


namespace PolicyManagementSystem.Controllers
{
    [Authorize]
    public class PolicyApplicationController : Controller
    {
        private IPolicyApplicationRepository _applicationRegistrationRepository;
        private IClientEngagementRepository _clientEngagementRepository;
        private IWebHostEnvironment _env;
        private IPolicyApplicationRepository _policyApplicationRepository;
        private IMemberApplicationRepository _memberApplicationRepository;
        private IUserAccountRepository _userAccountRepository;
        private IMapper _mapper;
        private readonly UserManager<IdentityUser> _userManager;






        public PolicyApplicationController(IMemberApplicationRepository memberApplicationRepository,
            IWebHostEnvironment env,IPolicyApplicationRepository applicationRegistrationRepository, 
            IClientEngagementRepository clientEngagementRepository, IUserAccountRepository userAccountRepository, IMapper mapper,
            UserManager<IdentityUser> userManager, IPolicyApplicationRepository policyApplicationRepository)
        {
            _applicationRegistrationRepository = applicationRegistrationRepository;
            _clientEngagementRepository = clientEngagementRepository;
            _env = env;
            _memberApplicationRepository = memberApplicationRepository;
            _userAccountRepository = userAccountRepository;
            _mapper = mapper;
            _userManager = userManager;
            _policyApplicationRepository = policyApplicationRepository;


        }

        [HttpGet]
        public IActionResult Index()
        {
            var notificationList = _clientEngagementRepository.GetBrokerNotificationList();
            var model = new PolicyApplicationViewModel() { BrokerNotificationList = notificationList };

            return View("~/Pages/PolicyApplication/Index.cshtml", model);
        }

        public IActionResult PolicyMemberList(int memPropNum)
        {
            var notificationList = _clientEngagementRepository.GetBrokerNotificationList();
            var model = new PolicyApplicationViewModel() { BrokerNotificationList = notificationList };

            var memberProposer = _policyApplicationRepository.MemberProposerGetById(memPropNum);
            return View("~/Pages/PolicyApplication/PolicyMemberList.cshtml");
        }
            //[HttpGet]
            //public IActionResult GetById(string email)
            //{
            //    var memberApplication = _memberApplicationRepository.MemberApplicationGetByEmail(email);
            //    var model = _mapper.Map<PolicyApplicationViewModel>(memberApplication);
            //    return Ok(model);
            //}
            [HttpPost]
        public IActionResult SavePrincipalMemberDetails(PolicyApplicationViewModel model)
        {
            var pibPolicies = _applicationRegistrationRepository.GetPIBPolicyList();

            var mtgPolicies = _applicationRegistrationRepository.GetMTGPolicyList();
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var memberApplication = _memberApplicationRepository.MemberApplicationGetByEmail(User.Identity.Name);
            if (pibPolicies != null)
            {
                model.AddPrincipalMemberDetails.CoverID = Convert.ToInt32(pibPolicies);
            }
            else if (mtgPolicies != null && pibPolicies == null)
            {
                model.AddPrincipalMemberDetails.CoverID = Convert.ToInt32(mtgPolicies);
            }
            if (memberApplication != null)
            {
                model.AddPrincipalMemberDetails.UserNum = Convert.ToInt32(memberApplication.MemDetNum);
                model.AddPrincipalMemberDetails.Title = memberApplication.Title;
                model.AddPrincipalMemberDetails.ContactPerson = memberApplication.FirstName;
                // model.PrincipalMemberDetails.M = memberApplication.MaidenName;
                model.AddPrincipalMemberDetails.Surname = memberApplication.Surname;
                model.AddPrincipalMemberDetails.Idnum = memberApplication.Idnum;
                model.AddPrincipalMemberDetails.CaptureDate = DateTime.Now.ToString();
                model.AddPrincipalMemberDetails.ContactEmail = memberApplication.Email;
                model.AddPrincipalMemberDetails.ContactCell = memberApplication.Phone;
                if (userId != null)
                {
                    model.AddPrincipalMemberDetails.UserID = userId;
                }

            }
            else
            {
                try
                {
                    _policyApplicationRepository.AddPrincipalMemberDetails(model.AddPrincipalMemberDetails);
                    //return Ok();
                }
                catch (Exception )
                {

                }
            }
            model.MemberProposer.UserId = Guid.Parse(userId);
            model.MemberProposer.Status = "Review";
            var memPropKey = _applicationRegistrationRepository.AddMemberProposer(model.MemberProposer);
            return View("~/Pages/PolicyApplication/Create.cshtml", model);

        }

      

        [HttpGet]
        public IActionResult Create()
        {
            var notificationList = _clientEngagementRepository.GetBrokerNotificationList();

            var memberApplication = _memberApplicationRepository.MemberApplicationGetByEmail(User.Identity.Name);

            var model = new PolicyApplicationViewModel() { BrokerNotificationList = notificationList };

            var pibPolicies = _applicationRegistrationRepository.GetPIBPolicyList();

            var mtgPolicies = _applicationRegistrationRepository.GetMTGPolicyList();
            

            //Populate policies
            model.PIBPolicies = pibPolicies.Select(a => new SelectListItem
            {
                Text = a.PlanID + " - Cover R" + a.CoverAmount,
                Value = Convert.ToString( a.PolicyCoverID)
            });

            model.MTGPolicies = mtgPolicies.Select(a => new SelectListItem
            {
                Text = a.PlanID + " - Cover R" + a.CoverAmount,
                Value = Convert.ToString(a.PolicyCoverID)
            });

            if (memberApplication != null)
            {
                var memberGroup = new MemberGroup();
                var memberProposer = new MemberProposer();
                memberGroup.ContactPerson = memberApplication.FirstName;
                memberGroup.MiddleName = memberApplication.MaidenName;
                memberGroup.Surname = memberApplication.Surname;
                memberGroup.Idnum = memberApplication.Idnum;
                memberGroup.Title = memberApplication.Title;
                memberGroup.ContactPhone = memberApplication.Phone;

                memberProposer.FirstName = memberApplication.FirstName;
                memberProposer.SecondName = memberApplication.MaidenName;
                memberProposer.Surname = memberApplication.Surname;
                memberProposer.Idnum = memberApplication.Idnum;
                memberProposer.Title = memberApplication.Title;
                memberProposer.ContactPhone = memberApplication.Phone;
                memberProposer.ContactEmail = memberApplication.Email;

                model.PrincipalMemberDetails = memberGroup;
                model.MemberProposer = memberProposer;

                return View("~/Pages/PolicyApplication/Create.cshtml", model);
            }
            else if(memberApplication== null)
            {

            }
            return View("~/Pages/PolicyApplication/Create.cshtml", model);
        }
        //Private helper methods
        private int CalculateAge(DateTime birthDay)
        {
            DateTime today = DateTime.Today;
            int age = today.Year - birthDay.Year;
            if (birthDay > today.AddYears(-age)) { 
            }

            return age;
        }
        private decimal CalculateTotal()
        {
            decimal total = 0;
            return total;
        }

        [HttpPost]
        public IActionResult Create(PolicyApplicationViewModel model, string submit, string save)
        {

            //check if its Print Summary
            if (submit == "Print")
            {
                TempData["member"] = model;

                return RedirectToAction("DownloadPIBContract", new { model = model });
            }

            try
            {
                //Start with the business rules before we start adding
                if (model.Beneficiary.Idnum == model.PrincipalMemberDetails.Idnum)
                {
                    ModelState.AddModelError("error", "Beneficiary ID must not be the same as the principal member");

                    return View("~/Pages/PolicyApplication/Create.cshtml", model);
                }

                if (model.MemberProposer.RelationToPrincipalMember == "Other(Specify)")
                {
                    model.MemberProposer.RelationToPrincipalMember = model.RelationOther;
                }
            
              
                //Get the logged in userId
                var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

                //Add the premium payer details
                model.MemberProposer.UserId = Guid.Parse(userId);

pib/dynamic/PolicyManagementSystem/Pages/PolicyApplication/ApplicationLocked.cshtml
@model PolicyManagementSystem.Controllers.Models.PolicyApplicationViewModel
<div class="row">
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
        <div class="page-header">
            <h2 class="pageheader-title">Policy Application</h2>
            <p class="pageheader-text"></p>
            <div class="page-breadcrumb">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        @*<li class="breadcrumb-item"><a href="#" class="breadcrumb-link">Dashboard</a></li>*@
                        <li class="breadcrumb-item"><a href="#" class="breadcrumb-link">Policy Application</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Application Locked</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
        <!-- ============================================================== -->
        <!-- overview -->
        <!-- ============================================================== -->
        <div class="page-section" id="overview">
            <div class="row">
                <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                    <h2>Policy Application Locked</h2>
                    <p class="lead">Sorry!! You you can't review the application now as its in : @Model.MemberProposer.Status.</p>
                    <br />
                    
                    @*<ul class="list-unstyled arrow">
                            <li> Lorem ipsum dolor sit amet, consectetur adipiscing elit.</li>
                            <li>Mauris bibendum massa ut porttitor congue.</li>
                            <li>Morbi condimentum magna eget facilisis accumsan.</li>
                            <li>Proin euismod eros nec libero efficitur, a dapibus mauris condimentum. </li>
                        </ul>*@
                </div>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- end overview -->
        <!-- ============================================================== -->
    </div>
</div>

pib/dynamic/PolicyManagementSystem/Pages/PolicyApplication/ApplicationSubmitted.cshtml
<div class="row">
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
        <div class="page-header">
            <h2 class="pageheader-title">Policy Application</h2>
            <p class="pageheader-text"></p>
            <div class="page-breadcrumb">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        @*<li class="breadcrumb-item"><a href="#" class="breadcrumb-link">Dashboard</a></li>*@
                        <li class="breadcrumb-item"><a href="#" class="breadcrumb-link">Policy Application</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Application Submitted</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
        <!-- ============================================================== -->
        <!-- overview -->
        <!-- ============================================================== -->
        <div class="page-section" id="overview">
            <div class="row">
                <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                    <h2>Policy Application Submitted</h2>
                    <p class="lead">Congratulations! Please note that your application has been submitted to the verification officer, please check your email, for the response. Thank you for choosing Us.</p>
                    @*<ul class="list-unstyled arrow">
                            <li> Lorem ipsum dolor sit amet, consectetur adipiscing elit.</li>
                            <li>Mauris bibendum massa ut porttitor congue.</li>
                            <li>Morbi condimentum magna eget facilisis accumsan.</li>
                            <li>Proin euismod eros nec libero efficitur, a dapibus mauris condimentum. </li>
                        </ul>*@
                </div>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- end overview -->
        <!-- ============================================================== -->
    </div>
</div>

pib/dynamic/PolicyManagementSystem/Pages/PolicyApplication/CreateApplication.cshtml
@model PolicyManagementSystem.Controllers.Models.PolicyApplicationViewModel
@{

}

<style>
    .clickedPlan {
        filter: grayscale(100%);
    }
</style>

<!-- ============================================================== -->
<!-- pageheader -->
<!-- ============================================================== -->
<div class="row">
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
        <div class="page-header">
            <h2 class="pageheader-title">Policy Application</h2>
            <p class="pageheader-text"></p>
            <div class="page-breadcrumb">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        @*<li class="breadcrumb-item"><a href="#" class="breadcrumb-link">Dashboard</a></li>*@
                        <li class="breadcrumb-item"><a href="#" class="breadcrumb-link">Policy Application</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Create Policy</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>
<div class="row">
   @using (Html.BeginForm("CreateApplication", "PolicyApplication", FormMethod.Post, new { @id = "CreatePolicy" }))
    {
        <ul class="nav nav-tabs" id="myTab" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Profile</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" id="contact-tab" data-toggle="tab" href="#contact" role="tab" aria-controls="contact" aria-selected="false">Contact</a>
            </li>
        </ul>
     
        <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">

            <div class="tab-content" id="myTabContent">
                <div class="form-group pib">
                    <label for="inputText3" class="col-form-label">Select Policy</label><br />
                    @Html.DropDownListFor(x => x.CoverID, new SelectList(Model.PIBPolicies, "Value", "Text"), new { @class = "form-control", })
                </div>
                <div class="form-group mtg" style="display:none;">
                    <label for="inputText3" class="col-form-label">Select Policy</label><br />

                    @Html.DropDownListFor(x => x.MTGCoverID, new SelectList(Model.MTGPolicies, "Value", "Text"), new { @class = "form-control" })
                </div>
                <div class="form-group">
                    <label for="inputText3" class="col-form-label">Title</label><br />
                    @Html.TextBoxFor(x => x.PrincipalMemberDetails.Title, new { @class = "form-control", placeholder = "Title" })
                </div>
                <div class="form-group">
                    <label for="inputText3" class="col-form-label">First Name</label><br />
                    @Html.TextBoxFor(x => x.PrincipalMemberDetails.ContactPerson, new { @class = "form-control", placeholder = "First Name" })
                </div>
                <div class="form-group">
                    <label for="inputText3" class="col-form-label">Maiden Name</label><br />
                    @Html.TextBoxFor(x => x.PrincipalMemberDetails.MiddleName, new { @class = "form-control", placeholder = "Maiden Name" })
                </div>
                <div class="form-group">
                    <label for="inputText3" class="col-form-label">Surname</label><br />
                    @Html.TextBoxFor(x => x.PrincipalMemberDetails.Surname, new { @class = "form-control", placeholder = "Surname" })
                </div>
                <div class="form-group">
                    <label for="inputText3" class="col-form-label">ID Number</label><br />
                    Index1.cshtml                            @Html.TextBoxFor(x => x.PrincipalMemberDetails.Idnum, new { @class = "form-control IDNo", placeholder = "SA ID/Passport", @maxlength = "15" })
                </div>
                <div class="form-group">
                    <label for="inputText3" class="col-form-label">Marital Status</label><br />
                    @Html.DropDownListFor(x => x.PrincipalMemberDetails.MaritalStatus, new List<SelectListItem>
                    {
                       new SelectListItem{ Text="Married", Value = "Married" },
                       new SelectListItem{ Text="Single", Value = "Single" },
                       new SelectListItem{ Text="Widow", Value = "Widow" }
                    }, new { @class = "form-control", @id = "ddlMaritalStatus" })
                </div>
                <div class="form-group">
                    <label for="inputText3" class="col-form-label">Cell Number</label><br />
                    @Html.TextBoxFor(x => x.PrincipalMemberDetails.ContactPhone, new { @class = "form-control", placeholder = "Cell Number" })
                </div>
            </div>
                <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">Something Else</div>
                <div class="tab-pane fade" id="contact" role="tabpanel" aria-labelledby="contact-tab">...</div>
              
            </div>
            }
        </div>

pib/dynamic/PolicyManagementSystem/Pages/PolicyApplication/Index.cshtml
@{

}
<!-- ============================================================== -->
<!-- pageheader -->
<!-- ============================================================== -->
<div class="row">
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
        <div class="page-header">
            <h2 class="pageheader-title">Policy Application</h2>
            <p class="pageheader-text"></p>
            <div class="page-breadcrumb">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        @*<li class="breadcrumb-item"><a href="#" class="breadcrumb-link">Dashboard</a></li>*@
                        <li class="breadcrumb-item"><a href="#" class="breadcrumb-link">Policy Application</a></li>
                        <li class="breadcrumb-item active" aria-current="page">List Applicantions</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <!-- ============================================================== -->
    <!-- basic table  -->
    <!-- ============================================================== -->

    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
        <div class="card">
            <h5 class="card-header">Policy Application</h5>
            <div class="card-body">
                <div class="table-responsive">
                    <a class="btn btn-primary btn-block" style="color:white" asp-controller="PolicyApplication" asp-action="Create">Create a policy</a>
                    <br />
                    <a class="btn btn-primary btn-block" style="color:white" asp-controller="CreateApplication" asp-action="CreateApplication">Apply For Policy</a>
                    <table class="table table-striped table-bordered first">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Title</th>
                                <th>Policy Type</th>
                                <th>Date</th>
                                <th>Telephone</th>
                                <th>Email</th>
                            </tr>
                        </thead>
                        <tbody>
                            @*@foreach (var user in Model.tblUseraccounts)
                {
                    <tr>
                        <td>@user.FldUsername</td>
                        <td>@user.FldUserTitle</td>
                        <td>@user.FldUserAccounttype</td>
                        <td>@user.FldUserDepartment</td>
                        <td>@user.FldUserJobtitle</td>
                        <td>
                            <a class="btn btn-primary btn-block" style="color:white" asp-route-id="@user.FldAccountId" asp-controller="UserManagement" asp-action="Edit">Edit</a>
                        </td>
                    </tr>
                }*@
                        </tbody>
                        <tfoot>
                            <tr>
                                <th>Name</th>
                                <th>Title</th>
                                <th>Policy Type</th>
                                <th>Date</th>
                                <th>Telephone</th>
                                <th>Email</th>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <!-- ============================================================== -->
    <!-- end basic table  -->
    <!-- ============================================================== -->
</div>

pib/dynamic/PolicyManagementSystem/Pages/PolicyApplication/PolicyAccepted.cshtml
@model PolicyManagementSystem.Controllers.Models.PolicyApplicationViewModel
<div class="row">
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
        <div class="page-header">
            <h2 class="pageheader-title">Policy Application</h2>
            <p class="pageheader-text"></p>
            <div class="page-breadcrumb">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        @*<li class="breadcrumb-item"><a href="#" class="breadcrumb-link">Dashboard</a></li>*@
                        <li class="breadcrumb-item"><a href="#" class="breadcrumb-link">Policy Application</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Application Accepted</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
        <!-- ============================================================== -->
        <!-- overview -->
        <!-- ============================================================== -->
        <div class="page-section" id="overview">
            <div class="row">
                <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                    <h2>Policy Application Accepted</h2>
                    <p class="lead">You have Accepted the Policy Application.</p>
                    <br />
                    @if (Model.IsStopOrder)
                    {
                        <a asp-route-id="@Model.MemberProposer.MemPropKey" asp-controller="PolicyApplication" asp-action="DownloadStopOrder" class="btn btn-secondary" style="background-color: #4656e9 !important; border-color: #4656e9 !important" value="Approve">Download Stop Order</a>
                        @*<a asp-route-id="@Model.MemberProposer.MemPropKey" asp-controller="PolicyApplication" asp-action="Edit" class="btn btn-secondary" style="background-color: #4656e9 !important; border-color: #4656e9 !important" value="Approve">Download Policy Profile</a>*@
                    }
                    <a asp-route-id="@Model.MemberProposer.MemPropKey" asp-controller="PolicyApplication" asp-action="DownloadPIBContract" class="btn btn-secondary" style="background-color: #4656e9 !important; border-color: #4656e9 !important" value="Approve">Download Policy Contract</a>
                    @*<ul class="list-unstyled arrow">
            <li> Lorem ipsum dolor sit amet, consectetur adipiscing elit.</li>
            <li>Mauris bibendum massa ut porttitor congue.</li>
            <li>Morbi condimentum magna eget facilisis accumsan.</li>
            <li>Proin euismod eros nec libero efficitur, a dapibus mauris condimentum. </li>
        </ul>*@
                </div>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- end overview -->
        <!-- ============================================================== -->
    </div>
</div>

pib/dynamic/PolicyManagementSystem/Pages/PolicyApplication/PolicyMemberList.cshtml
@model PolicyManagementSystem.Controllers.Models.PolicyApplicationViewModel
<div class="row">
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
        <div class="page-header">
            <h2 class="pageheader-title">Policy Application</h2>
            <p class="pageheader-text"></p>
            <div class="page-breadcrumb">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        @*<li class="breadcrumb-item"><a href="#" class="breadcrumb-link">Dashboard</a></li>*@
                        <li class="breadcrumb-item"><a href="#" class="breadcrumb-link">Policy Application</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Existing Policies</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
        <div class="card">
            <h5 class="card-header">Premium Members</h5>
            <div class="card-body">
                <div id="example4_filter" class="dataTables_filter">
                   @* <form action="ViewPolicy" method="post">
                        <input type="search" id="txtSearch" class="form-control form-control-sm" placeholder="Search" name="searchValue" aria-controls="example4">
                        <input type="submit" class="btn btn-secondary" style="background-color: #4656e9 !important; border-color: #4656e9 !important" value="Search">
                    </form>*@
                </div>
                <div class="table-responsive">
                    <table class="table table-striped table-bordered first">
                        <thead>
                            <tr>
                                <th>First Name</th>
                                <th>Surname</th>
                                <th>Contact Phone</th>
                                <th>Contact Email</th>
                                <th>Status</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var member in Model.MemberProposerList)
                            {
                            <tr>
                                <td>@member.FirstName</td>
                                <td>@member.Surname</td>
                                <td>@member.ContactPhone</td>
                                <td>@member.ContactEmail</td>
                                <td>@member.Status</td>
                                <td><a class="btn btn-primary btn-block" style="color:white" asp-route-id="@member.MemPropKey" asp-controller="PolicyApplication" asp-action="Edit">Ammend</a></td>
                            </tr>
                            }
                        </tbody>
                        @*<tfoot>
                            <tr>
                                <th>First Name</th>
                                <th>Surname</th>
                                <th>Contact Phone</th>
                                <th>Contact Email</th>
                                <th>Status</th>
                                <th></th>
                            </tr>
                        </tfoot>*@
                    </table>
                </div>
                <br />
                <div class="col-sm-12 col-md-7">
                    <div class="dataTables_paginate paging_simple_numbers" id="DataTables_Table_0_paginate">
                        <ul class="pagination">
                            @*<li class="paginate_button page-item previous disabled" id="DataTables_Table_0_previous"><a href="#" aria-controls="DataTables_Table_0" data-dt-idx="0" tabindex="0" class="page-link">Previous</a></li>*@

                            @for (int i = 1; i < 20; i++)
                            {
                                <li class="paginate_button page-item @(i == Model.CurrentPage ? "active" : "")"><a asp-route-currentPage="@i" asp-controller="PolicyApplication" asp-action="PolicyMemberList" aria-controls="DataTables_Table_0" data-dt-idx="@i" tabindex="0" class="page-link">@i</a></li>
                            }
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>